# base

PIPELINE = "pipeline"
STAGE = "stage"
SUCCESS = "success"
OUTPUT_DIR = "output_dir"
METRICS_PATH = "metrics_path"
ARTIFACTS = "artifacts"
WARNINGS = "warnings"
ERRORS = "errors"
GENERATED_AT = "generated_at"
META = "meta"
COUNTERS = "counters"
GUAGES = "gauges"
QUALITY = "quality"
PER_FILE = "per_file"
CONFIG_NAME = "config"
INPUT_FILES = "input_files"
FILES_PROCESSED = "files_processed"
FAILED_FILES = "failed_files"